# Generated by Django 4.1 on 2022-08-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authwiki', '0002_rename_library_comments_authwiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='authwiki',
            name='cover',
            field=models.FileField(blank=True, upload_to='covers/'),
        ),
    ]
